### ISSUE TITLE
Space doesn't work

### ISSUE THREAD

**Issue by JohnnyDes** [yohairosen/typeaheadFocus#1]
Hello!
Code works fine, but not with space. Space doesn't show any items from the list. When I change it to some letter, for example letter 'a' you code begin to work and showing me list of items with letter 'a'. Is there some possibility to make it work with space and show all results?

**Comment by yohairosen** [comment]
Hi @JohnnyDes,
By my code doesn't handle the typeahead directive actual logic, that's *Bootstrap*.
What it does is to initiate focus (the dropdown) when the user clicks on the input rather than when he start typing.
